<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="LBS MAM2021">
	<meta name="author" content="Brendan Kermorvan">
	<meta name="generator" content="Hugo 0.74.3" />
	<title>Pay discrimination at Omega Group PLC &middot; Portfolio website for Brendan Kermorvan</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="https://brendk.netlify.app/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="https://brendk.netlify.app/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="https://brendk.netlify.app/favicon.ico">
	<link rel="icon" type="image/x-icon" href="https://brendk.netlify.app/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="https://brendk.netlify.app/" class="logo"><strong>Brendan Kermorvan</strong> <span></span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="https://brendk.netlify.app/">Home</a></li>
            
                <li><a href="https://brendk.netlify.app/blogs">Blogs</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="https://brendk.netlify.app/blogs" class="button special fit">Get Started</a></li>
            
            
                <li><a href="https://brendk.netlify.app/" class="button fit">Log In</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Pay discrimination at Omega Group PLC</h1>
                            </header>
                            
                            
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="is-there-a-significant-difference-between-the-salaries-of-men-and-women-at-omega-group-plc" class="section level1">
<h1>Is there a significant difference between the salaries of men and women at Omega Group PLC ?</h1>
<p>Following the release of Omega Group PLC salary data, a quick analysis revealed that men executives salaries were USD 8’700 higher on average.</p>
<p>As it seems to be a considerable difference, we will investigate whether women executives are being discriminated in this company.</p>
<p>Shall we find a significant difference between the two groups, we will look at potential explanations to determine if other factors than gender can explain this difference.</p>
<p>First we will have a look at the dataframe.</p>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, ...
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, ...
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24...</code></pre>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>We calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, we show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% confidence interval.</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condifence interval

#Computing statistics
subset_male = omega[which(omega$gender == &quot;male&quot;),]
subset_female = omega[which(omega$gender == &quot;female&quot;),]

sd_male = sd(subset_male$salary)
sd_female = sd(subset_female$salary)
mean_male = mean(subset_male$salary)
mean_female = mean(subset_female$salary)
n_male = length(subset_male$salary)
n_female = length(subset_female$salary)
t_critical = 1.96
margin_error = 0.05

standard_error = sqrt((sd_female^2 / n_female) + (sd_male^2 / n_male))
t_statistic = (mean_female - mean_male) / standard_error
observed_difference = mean_female - mean_male
lb_95_CI = observed_difference - 2 * standard_error
ub_95_CI = observed_difference + 2 * standard_error

summary_statistics &lt;- data.frame(gender = c(&quot;male&quot;, &quot;female&quot;), mean = c(mean_male, mean_female), SD = c(sd_male, sd_female), sample_size = c(n_male, n_female), t_critical = c(t_critical, t_critical), standard_error = c(standard_error, standard_error), margin_error = c(margin_error, margin_error), lb_95_CI = c(lb_95_CI, lb_95_CI), ub_95_CI = c(ub_95_CI, ub_95_CI))

summary_statistics</code></pre>
<pre><code>##   gender  mean   SD sample_size t_critical standard_error margin_error lb_95_CI
## 1   male 73239 7463          24       1.96           2127         0.05   -12950
## 2 female 64543 7567          26       1.96           2127         0.05   -12950
##   ub_95_CI
## 1    -4443
## 2    -4443</code></pre>
<p>We tested the null hypothesis H0: mean males salary = mean females salary using a t-test. We computed a t-statistic of 4.09, which is greater than the t-critical value of 1.66 for a 5% error margin. Therefore, we can reject the null hypothesis H0 and state that the difference in mean salary we estimated in our sample is really different from zero. A 95% confidence interval for the difference between males and females mean salary is [4’443, 12’950].</p>
<p>We also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. We use hypothesis testing using t.test() and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using infer package
set.seed(1234)

obs_stat &lt;- omega %&gt;% 
  specify(salary ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;)

salaries_in_null_world &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;female&quot;, &quot;male&quot;))

salaries_in_null_world %&gt;% 
  visualize(bins = 15, method = &quot;simulation&quot;, obs_stat = obs_stat, direction=&quot;two sided&quot;)</code></pre>
<p><img src="/blogs/Omega_files/figure-html/hypothesis_testing,%20fig3-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>salaries_in_null_world %&gt;%
  get_p_value(obs_stat, direction = &quot;two sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>Both the t.test() method and infer package shows us that there is a high probability that the difference between males and females salaries is not equal to 0. We see on the above histogram that the observed difference of $8’696 is extreme. Furthermore, the p-value using both methods is less than 5%, indicating that the difference is statistically significant.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>We perform similar analyses than in previous sections using t.test() and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># hypothesis testing using infer package
set.seed(1234)

obs_stat &lt;- omega %&gt;% 
  specify(experience ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;)

salaries_in_null_world &lt;- omega %&gt;%
  specify(experience ~ gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;female&quot;, &quot;male&quot;))

salaries_in_null_world %&gt;% 
  visualize(bins = 15, method = &quot;simulation&quot;, obs_stat = obs_stat)</code></pre>
<p><img src="/blogs/Omega_files/figure-html/hypothesis-testing,%20fig5-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>salaries_in_null_world %&gt;%
  get_p_value(obs_stat, direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>Both methods shows that the difference in experience between male and female executives, 21.12 and 7.38 years respectively, is statistically significant at the 95% confidence level.</p>
<p>This result does not validate nor endanger our conclusion about the difference in male and female salaries, as experience may not impact salary at all. Let’s suppose that salary at Omega is only determined by gender, and that women are less experienced on average, we would observe significant difference in both male and female salaries and male and female experience. We therefore need to assess the relationship between experience and salary.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>We analyse the relationship between salary and experience by drawing a scatterplot to visually inspect the data.</p>
<pre class="r"><code>ggplot(omega, aes(x = experience, y = salary, color = gender)) + 
  geom_point(alpha = 0.3) +
  theme_bw() +
  geom_smooth()+
   labs(title = &quot;Scatter plot between years of experience and annual salary&quot;,
    y = &quot;Annual salary ($)&quot;,
    x = &quot;Years of experience at Omega&quot;)+
    theme(
    plot.title = element_text(hjust = 0.5, size = 12, face = &quot;bold&quot;)
  )</code></pre>
<p><img src="/blogs/Omega_files/figure-html/salary_exp_scatter,%20fig6-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(omega, aes(x = gender, y = experience)) + 
  geom_boxplot() +
  theme_bw() +
   labs(title = &quot;Years of experience repartition by gender&quot;,
    y = &quot;Years of experience&quot;,
    x = &quot;Gender&quot;)+
    theme(
    plot.title = element_text(hjust = 0.5, size = 12, face = &quot;bold&quot;)
  )</code></pre>
<p><img src="/blogs/Omega_files/figure-html/salary_exp_scatter,%20fig6-2.png" width="648" style="display: block; margin: auto;" /></p>
<p>The relationship between experience and salary at Omega is clearly positive. Female executives having up to 9 years experience appear to have an higher salary on average, but this effect can also be explained by the small number of men executives with less than 9 years of experience (Q3 experience for female = 14, Q1 experience for male = 15.75).
However, the salary of men executives with more than 9 years of experience seems higher on average.</p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>We use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to ggpairs() with aes arguments to colour by gender and make this plots somewhat transparent (alpha = 0.3).</p>
<pre class="r"><code>omega %&gt;% 
  #order variables as they will appear in ggpairs()
  select(gender, experience, salary) %&gt;% 
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/Omega_files/figure-html/ggpairs,%20fig7-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>From the salary vs experience scatterplot, we can infer that the relationship between experience and salary at Omega is positive.</p>
<p>Up to a certain level of experience, female executives tend to have an higher salary on average. This observation can be explained by looking at the boxplots of male and female executives experience.
However, men executives with more than 9 years of experience clearly have an higher salary on average.</p>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://www.twitter.com" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://www.instagram.com" class="icon alt fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
                
                    <li><a href="https://www.github.com" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="https://brendk.netlify.app/js/jquery.min.js"></script>
    <script src="https://brendk.netlify.app/js/jquery.scrolly.min.js"></script>
    <script src="https://brendk.netlify.app/js/jquery.scrollex.min.js"></script>
    <script src="https://brendk.netlify.app/js/skel.min.js"></script>
    <script src="https://brendk.netlify.app/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="https://brendk.netlify.app/js/main.js"></script>

    

    

    </body>
</html>
